/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

/**
 *
 * @author Shelin
 */
public class detail2 extends javax.swing.JFrame {

    /**
     * Creates new form detail2
     */
    public detail2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPenarikan = new javax.swing.JTextField();
        buttonTarik = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 24)); // NOI18N
        jLabel3.setText("BANK SK SYARIAH");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 210, 29);

        jLabel2.setFont(new java.awt.Font("Geometr212 BkCn BT", 0, 14)); // NOI18N
        jLabel2.setText("Penarikan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 60, 70, 18);

        jPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPenarikanActionPerformed(evt);
            }
        });
        jPanel1.add(jPenarikan);
        jPenarikan.setBounds(100, 100, 230, 30);

        buttonTarik.setText("OK");
        buttonTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTarikActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTarik);
        buttonTarik.setBounds(100, 140, 60, 23);

        jLabel5.setFont(new java.awt.Font("Geometr212 BkCn BT", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 70, 18);

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBack);
        buttonBack.setBounds(320, 290, 55, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPenarikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPenarikanActionPerformed

    private void buttonTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTarikActionPerformed
        String str, str1;
        int t, tab=50000;
        str1 = (jPenarikan.getText().toString());
        
        t = Integer.parseInt(str1);
        tarik mengambil = new tarik();
        mengambil.ambil(tab,t);
        tab = mengambil.getsaldo();
    }//GEN-LAST:event_buttonTarikActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        menu a = new menu();
        a.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonTarik;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPenarikan;
    // End of variables declaration//GEN-END:variables
}
